env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard-with-typescript
  - plugin:import/typescript
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules: {}
